#ifndef CONSTMAINWINDOW_H
#define CONSTMAINWINDOW_H

constexpr short NO_VALUE_SELECTED_ON_THE_TABLE = -1;
constexpr short SPEED_TIMER = 250;

constexpr short SPECIALITY_SELECTED_ON_THE_COMPANY_TABLE = 1;
constexpr short POST_SELECTED_ON_THE_COMPANY_TABLE = 2;
constexpr short SALARY_SELECTED_ON_THE_COMPANY_TABLE = 3;
constexpr short HOLIDAY_SELECTED_ON_THE_COMPANY_TABLE = 4;
constexpr short EDUCATION_SELECTED_ON_THE_COMPANY_TABLE= 5;
constexpr short MIN_AGE_SELECTED_ON_THE_COMPANY_TABLE = 6;
constexpr short MAX_AGE_SELECTED_ON_THE_COMPANY_TABLE = 7;

constexpr short DATE_SELECTED_ON_THE_PERSON_TABLE = 3;
constexpr short EDUCATION_SELECTED_ON_THE_PERSON_TABLE= 4;
constexpr short SPECIALITY_SELECTED_ON_THE_PERSON_TABLE = 5;
constexpr short POST_SELECTED_ON_THE_PERSON_TABLE = 6;
constexpr short SALARY_SELECTED_ON_THE_PERSON_TABLE = 7;



#endif // CONSTMAINWINDOW_H
